### PR TITLE
Explicitly set inter.broker.protocol.version to allow for kafka upgrade procedures.

### PR DESCRIPTION
**Pull request by SaaldjorMike**

### CODE REVIEW

**Review by mwl — APPROVED** [review]
Seems legit

**Comment by watsonian** [comment]
Could you add some comments around it explaining why we're setting it?

**Comment by SaaldjorMike** [comment]
> Could you add some comments around it explaining why we're setting it?

Certainly. Official Kafka docs states that when upgrading Kafka brokers, you must fix the `inter.broker.protocol.version` to the current/old version before upgrading the broker software. This way, all brokers in a cluster (being a mix of old and new broker software) will all communicate internally with the same protocol version. After all brokers have been upgraded to the new Kafka version, then `inter.broker.protocol.version` can be updated.
More info can be found here: https://kafka.apache.org/22/documentation.html#upgrade

I don't expect this role to be responsible for the entire upgrade flow, but having this variable allows us to create playbooks where we can do the upgrade flow described in the official documentation.

**Comment by SaaldjorMike** [comment]
@watsonian Do you have any comments on this before I merge it?

**Comment by watsonian** [comment]
@SaaldjorMike I still don't see any in-line comments. I'm mostly asking for this so any customers who see this know why it's there.

**Comment by SaaldjorMike** [comment]
> @SaaldjorMike I still don't see any in-line comments. I'm mostly asking for this so any customers who see this know why it's there.

For whatever reason I thought you wanted the comments in this issue and not in the server.properties file itself :-) I've added it now, let me know if there are anything else that I need to do before merging.

**Comment by watsonian** [comment]
Looks good! Thanks! 👍

**Pull request merged**
